-- Run with a development role permitted to create a database and schema.
CREATE DATABASE IF NOT EXISTS RISKLENS;
CREATE SCHEMA IF NOT EXISTS RISKLENS.DEMO;
USE DATABASE RISKLENS;
USE SCHEMA DEMO;
CREATE TABLE IF NOT EXISTS ACCOUNTS (
 ACCOUNT_ID VARCHAR, CUSTOMER_NAME VARCHAR, BASELINE_AMOUNT NUMBER(18,2)
);
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
 TRANSACTION_ID VARCHAR, ACCOUNT_ID VARCHAR, AMOUNT NUMBER(18,2), CURRENCY VARCHAR,
 TRANSACTION_TIME TIMESTAMP_NTZ, BENEFICIARY_ID VARCHAR, BENEFICIARY_AGE_DAYS INTEGER, DIRECTION VARCHAR
);
CREATE TABLE IF NOT EXISTS POLICIES (
 ID VARCHAR, NAME VARCHAR, VERSION VARCHAR, RULE VARCHAR, DESCRIPTION VARCHAR
);
