USE DATABASE RISKLENS;
USE SCHEMA DEMO;
CREATE OR REPLACE VIEW MONITORED_PAYMENTS AS
SELECT * FROM TRANSACTIONS WHERE DIRECTION='debit' AND CURRENCY='INR'
AND TRANSACTION_TIME >= '2026-09-01'::TIMESTAMP_NTZ
AND TRANSACTION_TIME < '2026-10-01'::TIMESTAMP_NTZ;

CREATE OR REPLACE VIEW SIGNAL_EVIDENCE AS
WITH large_payments AS (
 SELECT t.TRANSACTION_ID,t.ACCOUNT_ID,'POL-01' AS POLICY_ID
 FROM MONITORED_PAYMENTS t JOIN ACCOUNTS a ON t.ACCOUNT_ID=a.ACCOUNT_ID
 WHERE t.AMOUNT>=200000 AND t.AMOUNT>=5*a.BASELINE_AMOUNT
), burst_ends AS (
 SELECT endpoint.TRANSACTION_ID,endpoint.ACCOUNT_ID,endpoint.TRANSACTION_TIME
 FROM MONITORED_PAYMENTS endpoint JOIN MONITORED_PAYMENTS member
 ON endpoint.ACCOUNT_ID=member.ACCOUNT_ID
 AND member.TRANSACTION_TIME BETWEEN DATEADD('minute',-15,endpoint.TRANSACTION_TIME) AND endpoint.TRANSACTION_TIME
 GROUP BY endpoint.TRANSACTION_ID,endpoint.ACCOUNT_ID,endpoint.TRANSACTION_TIME
 HAVING COUNT(DISTINCT member.TRANSACTION_ID)>=4
), burst_payments AS (
 SELECT DISTINCT t.TRANSACTION_ID,t.ACCOUNT_ID,'POL-02' AS POLICY_ID
 FROM MONITORED_PAYMENTS t JOIN burst_ends b ON t.ACCOUNT_ID=b.ACCOUNT_ID
 AND t.TRANSACTION_TIME BETWEEN DATEADD('minute',-15,b.TRANSACTION_TIME) AND b.TRANSACTION_TIME
), new_beneficiaries AS (
 SELECT TRANSACTION_ID,ACCOUNT_ID,'POL-03' AS POLICY_ID FROM MONITORED_PAYMENTS
 WHERE BENEFICIARY_AGE_DAYS<=7 AND AMOUNT>=75000
)
SELECT * FROM large_payments UNION SELECT * FROM burst_payments UNION SELECT * FROM new_beneficiaries;

CREATE OR REPLACE VIEW FLAGGED_PAYMENTS AS
SELECT t.* FROM MONITORED_PAYMENTS t
WHERE EXISTS(SELECT 1 FROM SIGNAL_EVIDENCE e WHERE e.TRANSACTION_ID=t.TRANSACTION_ID);

CREATE OR REPLACE VIEW ACCOUNT_ALERTS AS
WITH totals AS (
 SELECT ACCOUNT_ID,COUNT(*) AS EVIDENCE_COUNT,SUM(AMOUNT) AS EXPOSURE,MAX(AMOUNT) AS MAX_AMOUNT
 FROM FLAGGED_PAYMENTS GROUP BY ACCOUNT_ID
), signals AS (
 SELECT ACCOUNT_ID,COUNT(DISTINCT POLICY_ID) AS SIGNAL_COUNT FROM SIGNAL_EVIDENCE GROUP BY ACCOUNT_ID
)
SELECT a.ACCOUNT_ID,a.CUSTOMER_NAME,a.BASELINE_AMOUNT,t.EVIDENCE_COUNT,t.EXPOSURE,s.SIGNAL_COUNT,
IFF(s.SIGNAL_COUNT>=2 OR t.MAX_AMOUNT>=500000,'High','Medium') AS SEVERITY
FROM ACCOUNTS a JOIN totals t ON a.ACCOUNT_ID=t.ACCOUNT_ID JOIN signals s ON a.ACCOUNT_ID=s.ACCOUNT_ID;
