-- Expected snapshot: 229 payments, INR 7,666,494 total,
-- 5 alerted accounts, 13 unique flagged payments, INR 2,170,000 flagged.
USE DATABASE RISKLENS;
USE SCHEMA DEMO;
SELECT COUNT(*)=229 AS PAYMENT_COUNT_OK,SUM(AMOUNT)=7666494 AS TOTAL_OK FROM MONITORED_PAYMENTS;
SELECT COUNT(*)=13 AS EVIDENCE_COUNT_OK,SUM(AMOUNT)=2170000 AS FLAGGED_AMOUNT_OK FROM FLAGGED_PAYMENTS;
SELECT COUNT(*)=5 AS ALERT_COUNT_OK FROM ACCOUNT_ALERTS;
SELECT ACCOUNT_ID,EXPOSURE,SIGNAL_COUNT,SEVERITY FROM ACCOUNT_ALERTS ORDER BY EXPOSURE DESC;
