-- Run All in the same worksheet where a warehouse is already selected.
-- Downloads only this public repository. No password, token or external data access is needed.
-- The Git integration allowlist is restricted to the RiskLens repository.
USE DATABASE RISKLENS;
USE SCHEMA DEMO;
SET RISKLENS_DEPLOY_WAREHOUSE = (SELECT CURRENT_WAREHOUSE());

CREATE API INTEGRATION IF NOT EXISTS RISKLENS_GITHUB_API
 API_PROVIDER = git_https_api
 API_ALLOWED_PREFIXES = ('https://github.com/MenigStar91/risklens-coco')
 ENABLED = TRUE;

CREATE GIT REPOSITORY IF NOT EXISTS RISKLENS_SOURCE
 API_INTEGRATION = RISKLENS_GITHUB_API
 ORIGIN = 'https://github.com/MenigStar91/risklens-coco';
ALTER GIT REPOSITORY RISKLENS_SOURCE FETCH;

CREATE STAGE IF NOT EXISTS RISKLENS_APP_SOURCE
 ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
COPY FILES INTO @RISKLENS_APP_SOURCE
 FROM @RISKLENS_SOURCE/branches/main/native/
 FILES = ('streamlit_app.py','environment.yml');

SET RISKLENS_CREATE_APP_SQL = (
 SELECT 'CREATE STREAMLIT IF NOT EXISTS RISKLENS.DEMO.RISKLENS_LIVE '
 || 'FROM ''@RISKLENS.DEMO.RISKLENS_APP_SOURCE'' '
 || 'MAIN_FILE = ''streamlit_app.py'' '
 || 'QUERY_WAREHOUSE = "' || REPLACE($RISKLENS_DEPLOY_WAREHOUSE,'"','""') || '" '
 || 'TITLE = ''RiskLens Live'''
);
EXECUTE IMMEDIATE $RISKLENS_CREATE_APP_SQL;
ALTER STREAMLIT RISKLENS.DEMO.RISKLENS_LIVE ADD LIVE VERSION FROM LAST;
SHOW STREAMLITS LIKE 'RISKLENS_LIVE' IN SCHEMA RISKLENS.DEMO;
