-- Read-only: run with ACCOUNTADMIN and share results (no secrets).
USE ROLE ACCOUNTADMIN;
SELECT CURRENT_ACCOUNT(), CURRENT_REGION(), CURRENT_ROLE(), CURRENT_WAREHOUSE();
SHOW COMPUTE POOLS;
SHOW COMPUTE POOL INSTANCE FAMILIES;
SHOW PARAMETERS LIKE 'STREAMLIT_EMBEDDING_CONTROLS' IN ACCOUNT;
DESCRIBE STREAMLIT RISKLENS.DEMO.RISKLENS_LIVE;
