-- Run as ACCOUNTADMIN. Keeps the existing app and database.
USE ROLE ACCOUNTADMIN;

ALTER ACCOUNT SET STREAMLIT_EMBEDDING_CONTROLS = $$
allowed_embedding_domains:
  - https://risklens-coco.menigstar91.chatgpt.site
$$;

CREATE ROLE IF NOT EXISTS RISKLENS_EMBED_MINTER;
CREATE USER IF NOT EXISTS RISKLENS_EMBED_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = RISKLENS_EMBED_MINTER;

GRANT ROLE RISKLENS_EMBED_MINTER TO USER RISKLENS_EMBED_SVC;
GRANT USAGE ON DATABASE RISKLENS TO ROLE RISKLENS_EMBED_MINTER;
GRANT USAGE ON SCHEMA RISKLENS.DEMO TO ROLE RISKLENS_EMBED_MINTER;
GRANT USAGE ON STREAMLIT RISKLENS.DEMO.RISKLENS_LIVE TO ROLE RISKLENS_EMBED_MINTER;
GRANT EMBED ON STREAMLIT RISKLENS.DEMO.RISKLENS_LIVE TO ROLE RISKLENS_EMBED_MINTER;

-- Private-key registration and runtime migration follow host preparation.
-- Do not change the app runtime yet.
SHOW GRANTS TO ROLE RISKLENS_EMBED_MINTER;
