-- In-place migration. Run only after 08_embedding_public_key.sql.
USE ROLE ACCOUNTADMIN;
USE DATABASE RISKLENS;
USE SCHEMA DEMO;

-- Preserve the current source for rollback.
CREATE STAGE IF NOT EXISTS RISKLENS_PRE_EMBED_BACKUP
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
COPY FILES INTO @RISKLENS_PRE_EMBED_BACKUP
  FROM 'snow://streamlit/RISKLENS.DEMO.RISKLENS_LIVE/versions/live/'
  FILES = ('streamlit_app.py', 'environment.yml');

ALTER GIT REPOSITORY RISKLENS_SOURCE FETCH;
COPY FILES INTO 'snow://streamlit/RISKLENS.DEMO.RISKLENS_LIVE/versions/live/'
  FROM @RISKLENS_SOURCE/branches/main/native_container/
  FILES = ('streamlit_app.py', 'pyproject.toml');

ALTER STREAMLIT RISKLENS.DEMO.RISKLENS_LIVE SET
  COMPUTE_POOL = SYSTEM_COMPUTE_POOL_CPU
  QUERY_WAREHOUSE = COMPUTE_WH
  RUNTIME_NAME = 'SYSTEM$ST_CONTAINER_RUNTIME_PY3_11';

ALTER STREAMLIT RISKLENS.DEMO.RISKLENS_LIVE COMMIT;
ALTER STREAMLIT RISKLENS.DEMO.RISKLENS_LIVE ADD LIVE VERSION FROM LAST;
DESCRIBE STREAMLIT RISKLENS.DEMO.RISKLENS_LIVE;

-- Rollback if needed (run separately, not as part of this script):
-- COPY FILES INTO 'snow://streamlit/RISKLENS.DEMO.RISKLENS_LIVE/versions/live/'
--   FROM @RISKLENS_PRE_EMBED_BACKUP FILES = ('streamlit_app.py', 'environment.yml');
-- ALTER STREAMLIT RISKLENS.DEMO.RISKLENS_LIVE SET RUNTIME_NAME = 'SYSTEM$WAREHOUSE_RUNTIME';
-- ALTER STREAMLIT RISKLENS.DEMO.RISKLENS_LIVE COMMIT;
-- ALTER STREAMLIT RISKLENS.DEMO.RISKLENS_LIVE ADD LIVE VERSION FROM LAST;
